### ISSUE TITLE
Update Unicode version

### ISSUE THREAD

**Issue by clarfonthey** [SimonSapin/rust-caseless#7]
Right now this crate uses Unicode 7.0.0 and should be updated to 10.0.0.

**Comment by SimonSapin** [comment]
Yes it should, though I’m not really working on this at the moment. Are you interested in making a pull request?

**Comment by clarfonthey** [comment]
After taking a look at the repo, it seems extremely straightforward. I'll grab the latest data and submit something tomorrow.

**Comment by clarfonthey** [comment]
This was closed by #8
